<!--
  Copyright (c) 2026 PCL N contributors.
  Licensed under the Apache License, Version 2.0.
-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>PCL.UI.Next.DevTools</AssemblyName>
    <RootNamespace>PCL.UI.Next.DevTools</RootNamespace>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <NoWarn>$(NoWarn);CA1716;CA1036;CA1512;CA1305;CA1720;CA1805;CA1822</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PCL.UI.Next\PCL.UI.Next.csproj" />
  </ItemGroup>
</Project>

