// Copyright (c) MUXUE1230. All rights reserved.
// Modifications Copyright (c) 2026 PCL N contributors.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace PCL.Desktop.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class BuildInfoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<BuildInfoModel> buildInfo = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, cancellationToken) => GetBuildInfo(provider, cancellationToken));

        context.RegisterSourceOutput(buildInfo, static (spc, info) => GenerateBuildInfo(spc, info));
    }

    private static BuildInfoModel GetBuildInfo(
        AnalyzerConfigOptionsProvider provider,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        string informationalVersion = GetProperty(provider.GlobalOptions, "InformationalVersion");
        string version = GetProperty(provider.GlobalOptions, "Version");
        string sourceRevisionId = GetProperty(provider.GlobalOptions, "SourceRevisionId");
        string runtimeVariant = GetProperty(provider.GlobalOptions, "PclRuntimeVariant");
        string includesPlugin = GetProperty(provider.GlobalOptions, "PclIncludesPlugin");

        if (string.IsNullOrWhiteSpace(informationalVersion))
            informationalVersion = string.IsNullOrWhiteSpace(version) ? "dev" : version;

        string displayVersion = StripBuildMetadata(informationalVersion);
        if (string.IsNullOrWhiteSpace(displayVersion))
            displayVersion = "dev";

        return new BuildInfoModel(
            informationalVersion,
            version,
            sourceRevisionId,
            displayVersion,
            string.IsNullOrWhiteSpace(runtimeVariant) ? "SelfContained" : runtimeVariant,
            string.Equals(includesPlugin, "true", StringComparison.OrdinalIgnoreCase));
    }

    private static void GenerateBuildInfo(SourceProductionContext context, BuildInfoModel info)
    {
        StringBuilder sb = new(1024);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// 此文件由 Source Generator 自动生成，请勿手动修改");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PCL.Desktop;");
        sb.AppendLine();
        sb.AppendLine("internal static class PclBuildInfo");
        sb.AppendLine("{");
        AppendConstant(sb, "InformationalVersion", info.InformationalVersion);
        AppendConstant(sb, "Version", info.Version);
        AppendConstant(sb, "SourceRevisionId", info.SourceRevisionId);
        AppendConstant(sb, "DisplayVersion", info.DisplayVersion);
        AppendConstant(sb, "RuntimeVariant", info.RuntimeVariant);
        sb.Append("    public const bool IncludesPlugin = ")
            .Append(info.IncludesPlugin ? "true" : "false")
            .AppendLine(";");
        sb.AppendLine("}");

        context.AddSource(
            "PclBuildInfo.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendConstant(StringBuilder sb, string name, string value)
    {
        sb.Append("    public const string ")
            .Append(name)
            .Append(" = ")
            .Append(SymbolDisplay.FormatLiteral(value, quote: true))
            .AppendLine(";");
    }

    private static string GetProperty(AnalyzerConfigOptions options, string name) =>
        options.TryGetValue("build_property." + name, out string? value) ? value ?? string.Empty : string.Empty;

    private static string StripBuildMetadata(string version)
    {
        int metadataIndex = version.IndexOf('+');
        return metadataIndex > 0 ? version.Substring(0, metadataIndex) : version;
    }

    private sealed class BuildInfoModel
    {
        public BuildInfoModel(
            string informationalVersion,
            string version,
            string sourceRevisionId,
            string displayVersion,
            string runtimeVariant,
            bool includesPlugin)
        {
            InformationalVersion = informationalVersion;
            Version = version;
            SourceRevisionId = sourceRevisionId;
            DisplayVersion = displayVersion;
            RuntimeVariant = runtimeVariant;
            IncludesPlugin = includesPlugin;
        }

        public string InformationalVersion { get; }

        public string Version { get; }

        public string SourceRevisionId { get; }

        public string DisplayVersion { get; }

        public string RuntimeVariant { get; }

        public bool IncludesPlugin { get; }
    }
}
