// Copyright (c) 2026 PCL N contributors.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace PCL.Desktop.SourceGenerators;

/// <summary>
/// Compiles the deterministic OOBE manifest into typed code. The launcher no
/// longer parses its shipped default configuration during startup.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OobeConfigurationGenerator : IIncrementalGenerator
{
    private const string FileName = "pcln-oobe.default.json";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<OobeModel> model = context.AdditionalTextsProvider
            .Where(static file => string.Equals(
                Path.GetFileName(file.Path),
                FileName,
                StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) => Parse(
                file.GetText(cancellationToken)?.ToString() ?? string.Empty))
            .Collect()
            .Select(static (items, _) => items.Length > 0 ? items[0] : OobeModel.Fallback);

        context.RegisterSourceOutput(model, static (productionContext, value) =>
        {
            productionContext.AddSource(
                "PclCompiledOobeConfiguration.g.cs",
                SourceText.From(Generate(value), Encoding.UTF8));
        });
    }

    private static OobeModel Parse(string json)
    {
        string contentVersion = MatchString(json, "contentVersion") ?? "4";
        string[] full = NormalizeSteps(MatchStringArray(json, "fullSteps"), OobeModel.Fallback.FullSteps);
        string[] update = NormalizeSteps(MatchStringArray(json, "updateSteps"), OobeModel.Fallback.UpdateSteps);
        bool restartAfterFull = MatchBoolean(json, "restartAfterFull") ?? true;
        bool restartAfterUpdate = MatchBoolean(json, "restartAfterUpdate") ?? false;
        return new OobeModel(contentVersion, full, update, restartAfterFull, restartAfterUpdate);
    }

    private static string Generate(OobeModel model)
    {
        StringBuilder source = new(2048);
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace PCL.Desktop.Views.FirstRun;");
        source.AppendLine();
        source.AppendLine("internal static class PclCompiledOobeConfiguration");
        source.AppendLine("{");
        source.Append("    public const string ContentVersion = ")
            .Append(SymbolDisplay.FormatLiteral(model.ContentVersion, quote: true))
            .AppendLine(";");
        source.Append("    public const bool RestartAfterFull = ")
            .Append(model.RestartAfterFull ? "true" : "false")
            .AppendLine(";");
        source.Append("    public const bool RestartAfterUpdate = ")
            .Append(model.RestartAfterUpdate ? "true" : "false")
            .AppendLine(";");
        AppendFactory(source, "CreateFullSteps", model.FullSteps);
        AppendFactory(source, "CreateUpdateSteps", model.UpdateSteps);
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendFactory(StringBuilder source, string name, IReadOnlyList<string> steps)
    {
        source.Append("    public static global::System.Collections.Generic.IReadOnlyList<OobeStepId> ")
            .Append(name)
            .AppendLine("() =>");
        source.AppendLine("    [");
        foreach (string step in steps)
        {
            source.Append("        OobeStepId.")
                .Append(step)
                .AppendLine(",");
        }
        source.AppendLine("    ];");
    }

    private static string? MatchString(string json, string property)
    {
        Match match = Regex.Match(
            json,
            "\\\"" + Regex.Escape(property) + "\\\"\\s*:\\s*\\\"(?<value>[^\\\"]*)\\\"",
            RegexOptions.CultureInvariant);
        return match.Success ? match.Groups["value"].Value.Trim() : null;
    }

    private static string[] MatchStringArray(string json, string property)
    {
        Match array = Regex.Match(
            json,
            "\\\"" + Regex.Escape(property) + "\\\"\\s*:\\s*\\[(?<value>.*?)\\]",
            RegexOptions.CultureInvariant | RegexOptions.Singleline);
        if (!array.Success)
            return Array.Empty<string>();

        return Regex.Matches(array.Groups["value"].Value, "\\\"(?<value>[^\\\"]+)\\\"")
            .Cast<Match>()
            .Select(static match => match.Groups["value"].Value.Trim())
            .Where(static value => value.Length > 0)
            .ToArray();
    }

    private static bool? MatchBoolean(string json, string property)
    {
        Match match = Regex.Match(
            json,
            "\\\"" + Regex.Escape(property) + "\\\"\\s*:\\s*(?<value>true|false)",
            RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);
        return match.Success ? string.Equals(match.Groups["value"].Value, "true", StringComparison.OrdinalIgnoreCase) : null;
    }

    private static string[] NormalizeSteps(IEnumerable<string> values, IReadOnlyList<string> fallback)
    {
        List<string> result = new();
        foreach (string value in values)
        {
            string? step = value.Trim().ToLowerInvariant() switch
            {
                "welcome" or "start" => "Welcome",
                "terms" or "legal-terms" or "tos" => "Terms",
                "privacy" or "legal-privacy" => "Privacy",
                "data" or "datapaths" or "data-paths" or "paths" => "DataPaths",
                "online" or "account" or "cloud" => "Online",
                "telemetry" or "privacy-telemetry" => "Telemetry",
                "finish" or "done" or "complete" => "Finish",
                // Compatibility was removed from the product and must not reappear
                // merely because an older checked-in manifest still mentions it.
                _ => null
            };
            if (step is not null && !result.Contains(step, StringComparer.Ordinal))
                result.Add(step);
        }

        if (result.Count == 0)
            return fallback.ToArray();
        if (!result.Contains("Finish", StringComparer.Ordinal))
            result.Add("Finish");
        return result.ToArray();
    }

    private sealed class OobeModel
    {
        public static OobeModel Fallback { get; } = new(
            "4",
            new[] { "Welcome", "Terms", "Privacy", "DataPaths", "Online", "Telemetry", "Finish" },
            new[] { "Welcome", "Finish" },
            true,
            false);

        public OobeModel(
            string contentVersion,
            string[] fullSteps,
            string[] updateSteps,
            bool restartAfterFull,
            bool restartAfterUpdate)
        {
            ContentVersion = contentVersion;
            FullSteps = fullSteps;
            UpdateSteps = updateSteps;
            RestartAfterFull = restartAfterFull;
            RestartAfterUpdate = restartAfterUpdate;
        }

        public string ContentVersion { get; }
        public string[] FullSteps { get; }
        public string[] UpdateSteps { get; }
        public bool RestartAfterFull { get; }
        public bool RestartAfterUpdate { get; }
    }
}
