<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Description>Focused executable tests for the Sidecar protocol and transport.</Description>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../PCL.Sidecar.Protocol/PCL.Sidecar.Protocol.csproj" />
  </ItemGroup>
</Project>
